on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Navigate to Dashboard directory
        run: cd Dashboard
      - name: Install NPM dependencies
        run: npm install
        working-directory: ./Dashboard
      - name: Run tests
        run: npm test
        working-directory: ./Dashboard
  automerge:
    needs: test
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Automerge
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
